import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, Check, ChevronDown, CircleHelp, Clock3, CreditCard, Home, MapPin, Minus, Plus, Search, ShoppingBag, Trash2, UtensilsCrossed, X, RotateCcw, PackageCheck, ShieldCheck, Menu as MenuIcon, Smartphone, Monitor, Info } from "lucide-react";
import { Button } from "@/components/ui/button";
import adobo from "@/assets/chicken-adobo.jpg";
import sisig from "@/assets/pork-sisig.jpg";
import tapa from "@/assets/beef-tapa.jpg";

type Screen = "home" | "menu" | "detail" | "cart" | "failed" | "tracking";
type Item = { id: number; name: string; description: string; price: number; image: string; category: string; time: string };
type CartItem = { item: Item; qty: number; size: string };
const items: [Item, ...Item[]] = [
  { id: 1, name: "Chicken Adobo Bowl", description: "Soy-braised chicken, garlic rice, egg & scallions", price: 189, image: adobo, category: "Rice bowls", time: "20–30 min" },
  { id: 2, name: "Sizzling Pork Sisig", description: "Crispy pork, calamansi, onions & sunny-side egg", price: 219, image: sisig, category: "Favorites", time: "25–35 min" },
  { id: 3, name: "Beef Tapa Silog", description: "Sweet-savory beef, garlic rice, egg & tomato", price: 209, image: tapa, category: "Rice bowls", time: "20–30 min" },
];
const categories = ["All", "Rice bowls", "Favorites", "Breakfast"];
const peso = (value: number) => `₱${value.toFixed(2)}`;
const guide = [
  { n: "01", title: "Visibility of system status", screen: "tracking" as Screen, evidence: "Live order stages and an estimated arrival time show what is happening now.", target: "tracking" },
  { n: "02", title: "Match with the real world", screen: "menu" as Screen, evidence: "Familiar dish names, food photography, prices in pesos, and preparation times speak the customer's language.", target: "food" },
  { n: "03", title: "User control & freedom", screen: "cart" as Screen, evidence: "Remove a dish and an Undo toast lets you reverse the action immediately.", target: "undo" },
  { n: "04", title: "Consistency & standards", screen: "menu" as Screen, evidence: "The same food cards, orange add controls, navigation, and cart badge work throughout the app.", target: "food" },
  { n: "05", title: "Error prevention", screen: "detail" as Screen, evidence: "A size is chosen before adding, and the order total remains visible before confirmation.", target: "size" },
  { n: "06", title: "Recognition over recall", screen: "home" as Screen, evidence: "Popular dishes show their photos, names, and prices together instead of making you remember a previous screen.", target: "popular" },
  { n: "07", title: "Flexibility & efficiency", screen: "home" as Screen, evidence: "Search, category shortcuts, and one-tap quick add support both browsing and fast repeat orders.", target: "shortcut" },
  { n: "08", title: "Aesthetic & minimalist design", screen: "home" as Screen, evidence: "A clear hierarchy, restrained color, and only essential ordering information keep the view focused.", target: "minimal" },
  { n: "09", title: "Recover from errors", screen: "failed" as Screen, evidence: "The failed payment says why it stopped and offers retry, change payment, and help.", target: "recovery" },
  { n: "10", title: "Help & documentation", screen: "home" as Screen, evidence: "The question-mark button opens concise answers and a way to get assistance.", target: "help" },
];

export default function KainGoApp() {
  const [screen, setScreen] = useState<Screen>("home");
  const [selected, setSelected] = useState(items[0]);
  const [cart, setCart] = useState<CartItem[]>([]);
  const [category, setCategory] = useState("All");
  const [query, setQuery] = useState("");
  const [size, setSize] = useState("Regular");
  const [qty, setQty] = useState(1);
  const [address, setAddress] = useState("Home");
  const [payment, setPayment] = useState("Visa ending in 4242");
  const [toast, setToast] = useState<CartItem | null>(null);
  const [helpOpen, setHelpOpen] = useState(false);
  const [dialog, setDialog] = useState(false);
  const [guideOpen, setGuideOpen] = useState(true);
  const [activeGuide, setActiveGuide] = useState<number | null>(null);
  const [calloutsVisible, setCalloutsVisible] = useState(true);
  const [framed, setFramed] = useState(true);
  const [retrying, setRetrying] = useState(false);
  const [orderNumber, setOrderNumber] = useState(1048);
  const count = cart.reduce((sum, line) => sum + line.qty, 0);
  const subtotal = cart.reduce((sum, line) => sum + (line.item.price + (line.size === "Large" ? 40 : 0)) * line.qty, 0);
  const total = subtotal + (cart.length ? 39 : 0);
  const navigate = (next: Screen) => { setScreen(next); setToast(null); setHelpOpen(false); setDialog(false); setRetrying(false); };
  useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(null), 5500); return () => window.clearTimeout(timer); }, [toast]);
  const openDetail = (item: Item) => { setSelected(item); setSize("Regular"); setQty(1); navigate("detail"); };
  const add = (item: Item, amount = 1, chosenSize = "Regular") => {
    setCart(previous => {
      const matching = previous.find(line => line.item.id === item.id && line.size === chosenSize);
      if (matching) return previous.map(line => line === matching ? { ...line, qty: line.qty + amount } : line);
      return [...previous, { item, qty: amount, size: chosenSize }];
    });
    setToast(null);
  };
  const remove = (index: number) => { const removed = cart[index]; if (!removed) return; setToast(removed); setCart(previous => previous.filter((_, i) => i !== index)); };
  const selectGuide = (index: number) => { const entry = guide[index]; if (!entry) return; setActiveGuide(index); navigate(entry.screen); };
  const back = () => navigate(screen === "detail" ? "menu" : screen === "failed" ? "cart" : "home");
  const badge = <span className="kg-badge">{count}</span>;
  const iconButton = (label: string, icon: React.ReactNode, action: () => void, extra?: React.ReactNode) => <Button variant="outline" size="icon" className={`kg-icon-button ${label === "Help" ? highlighted("help") : ""}`} aria-label={label} title={label} onClick={action}>{icon}{extra}</Button>;
  const highlighted = (key: string) => activeGuide !== null && guide[activeGuide]?.target === key ? "kg-highlight" : "";
  const foodCard = (item: Item, mode: "menu" | "cart" = "menu", index = 0) => <div className={`kg-food-card ${highlighted("food")}`} key={`${item.id}-${index}`}>
    <img src={item.image} width={52} height={52} loading="lazy" alt={item.name} className="kg-food-thumb" onClick={() => mode === "menu" && openDetail(item)} />
    <div className="kg-food-copy" onClick={() => mode === "menu" && openDetail(item)}><strong>{item.name}</strong><span>{mode === "cart" ? `${cart[index]?.size} · ${peso(item.price + (cart[index]?.size === "Large" ? 40 : 0))} each` : `${peso(item.price)} · ${item.time}`}</span></div>
    {mode === "menu" ? <Button size="icon" className="kg-quick-add" aria-label={`Add ${item.name} to cart`} title={`Add ${item.name}`} onClick={() => add(item)}><Plus size={20}/></Button> : <div className="kg-cart-actions"><span className="kg-quantity">×{cart[index]?.qty}</span><Button variant="ghost" size="icon" className="kg-remove" aria-label={`Remove ${item.name}`} title={`Remove ${item.name}`} onClick={() => remove(index)}><X size={18}/></Button></div>}
  </div>;

  return <div className="kg-workspace">
    <header className="kg-workspace-header"><div className="kg-brand"><span className="kg-brand-mark"><UtensilsCrossed size={17}/></span><span>Kain<span className="kg-brand-accent">Go</span></span><span className="kg-header-divider"/><span className="kg-header-label">Interactive prototype</span></div><div className="kg-header-actions"><span className="kg-frame-label">390 × 844</span><Button variant="ghost" size="icon" className="kg-workspace-icon" title={framed ? "Hide device frame" : "Show device frame"} aria-label={framed ? "Hide device frame" : "Show device frame"} onClick={() => setFramed(!framed)}>{framed ? <Smartphone size={19}/> : <Monitor size={19}/>}</Button><Button variant="outline" className={`kg-callout-toggle ${calloutsVisible ? "is-on" : ""}`} aria-label={calloutsVisible ? "Hide in-app callouts" : "Show in-app callouts"} title={calloutsVisible ? "Hide in-app callouts" : "Show in-app callouts"} aria-pressed={calloutsVisible} onClick={() => setCalloutsVisible(!calloutsVisible)}><Info size={15}/> Callouts {calloutsVisible ? "on" : "off"}</Button><Button variant={guideOpen ? "default" : "outline"} className="kg-guide-toggle" onClick={() => setGuideOpen(!guideOpen)}><Info size={15}/> Heuristics guide</Button></div></header>
    <main className="kg-stage">
      <aside className="kg-screen-rail"><div className="kg-rail-heading">SCREENS <span>06</span></div>{(["home", "menu", "detail", "cart", "failed", "tracking"] as Screen[]).map((s, i) => <Button key={s} variant="ghost" className={`kg-screen-link ${screen === s ? "is-active" : ""}`} onClick={() => navigate(s)}><span className="kg-screen-index">0{i+1}</span><span>{({home:"Home",menu:"Explore menu",detail:"Item details",cart:"Your cart",failed:"Payment failed",tracking:"Order tracking"} as Record<Screen,string>)[s]}</span>{screen === s && <ArrowRight size={14}/>}</Button>)}<div className="kg-rail-note"><span className="kg-note-line"/>Click through the flow or jump straight to any screen.</div></aside>
      <div className={`kg-device-wrap ${framed ? "is-framed" : ""}`}><div className="kg-device"><div className="kg-statusbar"><span>9:41</span><span className="kg-status-icons"><span className="kg-signal">▂▄▆</span><span className="kg-wifi">◕</span><span className="kg-battery"/></span></div>
        <div className="kg-app-scroll" key={screen}>
          {screen === "home" && <div className="kg-screen kg-home"><div className="kg-topline"><div><span className="kg-caption kg-muted">DELIVERING TO</span><Button variant="ghost" className="kg-address-link" onClick={() => navigate("cart")}><MapPin size={15} fill="currentColor"/> Home <ChevronDown size={14}/></Button></div><div className="kg-top-actions">{iconButton("Help", <CircleHelp size={19}/>, () => setHelpOpen(true))}{iconButton("Cart", <ShoppingBag size={18}/>, () => navigate("cart"), count > 0 && badge)}</div></div>
            <div className={highlighted("minimal")}><p className="kg-greeting">Good afternoon, foodie <span>✳</span></p><h1>What are you<br/>craving today?</h1></div>
            <Button variant="outline" className={`kg-search-trigger ${highlighted("shortcut")}`} onClick={() => { setCategory("All"); navigate("menu"); }}><Search size={18}/> Search dishes, cuisines...</Button>
            <div className="kg-promo"><div className="kg-promo-copy"><span className="kg-promo-eyebrow">TODAY'S PICK</span><h2>A little comfort<br/>in every bite.</h2><Button variant="secondary" className="kg-promo-button" onClick={() => openDetail(items[0])}>Order now <ArrowRight size={15}/></Button></div><img src={adobo} width={160} height={160} alt="Chicken adobo bowl" /></div>
            <div className="kg-section-heading"><h2>What sounds good?</h2><Button variant="ghost" onClick={() => navigate("menu")}>See all <ArrowRight size={14}/></Button></div><div className={`kg-category-grid ${highlighted("shortcut")}`}><Button variant="outline" onClick={() => {setCategory("Rice bowls");navigate("menu")}}><span><UtensilsCrossed size={20}/></span> Rice bowls</Button><Button variant="outline" onClick={() => {setCategory("Favorites");navigate("menu")}}><span><ShieldCheck size={20}/></span> Favorites</Button></div>
            <div className="kg-section-heading"><h2>Popular right now</h2><Button variant="ghost" onClick={() => navigate("menu")}>See all <ArrowRight size={14}/></Button></div><div className={highlighted("popular")}>{items.slice(0,2).map(item => foodCard(item))}</div>
          </div>}
          {screen === "menu" && <div className="kg-screen"><div className="kg-page-header"><div><span className="kg-overline">HUNGRY? WE'VE GOT YOU.</span><h1>Explore menu</h1></div>{iconButton("Cart", <ShoppingBag size={18}/>, () => navigate("cart"), count > 0 && badge)}</div><label className="kg-search-field"><Search size={18}/><input placeholder="Search for something delicious" value={query} onChange={event => setQuery(event.target.value)} aria-label="Search menu" />{query && <Button variant="ghost" size="icon" aria-label="Clear search" onClick={() => setQuery("")}><X size={15}/></Button>}</label><div className="kg-chips">{categories.map(cat => <Button key={cat} variant="outline" className={`kg-chip ${category === cat ? "is-selected" : ""}`} onClick={() => setCategory(cat)}>{cat}</Button>)}</div><div className="kg-menu-intro"><span>{category === "All" ? "All dishes" : category}</span><span>{items.filter(item => (category === "All" || item.category === category || category === "Breakfast" && item.id === 3) && `${item.name} ${item.description}`.toLowerCase().includes(query.toLowerCase())).length} dishes</span></div><div className="kg-menu-list">{items.filter(item => (category === "All" || item.category === category || category === "Breakfast" && item.id === 3) && `${item.name} ${item.description}`.toLowerCase().includes(query.toLowerCase())).map(item => foodCard(item))}</div>{items.filter(item => (category === "All" || item.category === category || category === "Breakfast" && item.id === 3) && `${item.name} ${item.description}`.toLowerCase().includes(query.toLowerCase())).length === 0 && <div className="kg-empty"><Search size={28}/><strong>No dishes found</strong><span>Try a different search or category.</span><Button variant="outline" onClick={() => {setQuery("");setCategory("All")}}>Show all dishes</Button></div>}<div className="kg-menu-feature"><span>MADE WITH CARE</span><p>Good food, right to your door.</p></div></div>}
          {screen === "detail" && <div className="kg-detail"><div className="kg-detail-photo"><img src={selected.image} width={390} height={390} alt={selected.name}/><div className="kg-detail-actions">{iconButton("Back to menu", <ArrowLeft size={19}/>, back)}{iconButton("Help", <CircleHelp size={19}/>, () => setHelpOpen(true))}</div></div><div className="kg-detail-sheet"><div className="kg-sheet-handle"/><div className="kg-detail-heading"><div><span className="kg-overline">FRESHLY MADE · {selected.time.toUpperCase()}</span><h1>{selected.name}</h1></div><span className="kg-price">{peso(selected.price)}</span></div><p className="kg-detail-desc">{selected.description}. Made fresh and packed with all the flavors you love.</p><div className="kg-divider"/><div className={highlighted("size")}><div className="kg-option-heading"><h2>Choose your size</h2><span>Required</span></div>{["Regular", "Large"].map(option => <Button key={option} variant="outline" className={`kg-option ${size === option ? "is-selected" : ""}`} onClick={() => setSize(option)}><span className="kg-radio">{size === option && <span/>}</span><span>{option}</span><span className="kg-option-price">{option === "Regular" ? "Included" : "+ ₱40.00"}</span></Button>)}</div><div className="kg-quantity-row"><span>Quantity</span><div><Button variant="outline" size="icon" aria-label="Decrease quantity" disabled={qty === 1} onClick={() => setQty(qty - 1)}><Minus size={16}/></Button><strong>{qty}</strong><Button variant="outline" size="icon" aria-label="Increase quantity" onClick={() => setQty(qty + 1)}><Plus size={16}/></Button></div></div></div></div>}
          {screen === "cart" && <div className="kg-screen kg-cart-screen"><div className="kg-page-header kg-cart-header">{iconButton("Back", <ArrowLeft size={19}/>, back)}<h1>Your cart</h1>{iconButton("Help", <CircleHelp size={19}/>, () => setHelpOpen(true))}</div>{cart.length ? <><div className="kg-cart-count">YOUR ORDER <span>{count} {count === 1 ? "ITEM" : "ITEMS"}</span></div><div className="kg-cart-list">{cart.map((line, index) => foodCard(line.item, "cart", index))}</div><Button variant="ghost" className="kg-add-more" onClick={() => navigate("menu")}><Plus size={16}/> Add more dishes</Button><div className="kg-cart-divider"/><h2 className="kg-cart-section-title">Delivery details</h2><span className="kg-field-label">DELIVER TO</span><div className="kg-two-options">{["Home", "Office"].map(option => <Button key={option} variant="outline" className={`kg-option kg-small-option ${address === option ? "is-selected" : ""}`} onClick={() => setAddress(option)}><MapPin size={16}/>{option}{address === option && <Check size={15}/>}</Button>)}</div><p className="kg-address-detail">{address === "Home" ? "123 Mabini St, Makati City" : "88 Ayala Ave, Makati City"}</p><span className="kg-field-label">PAY WITH</span><div className="kg-two-options">{["Visa ending in 4242", "Cash"].map(option => <Button key={option} variant="outline" className={`kg-option kg-small-option ${payment === option ? "is-selected" : ""}`} onClick={() => setPayment(option)}><CreditCard size={16}/><span>{option === "Visa ending in 4242" ? "Visa ···4242" : "Cash"}</span>{payment === option && <Check size={15}/>}</Button>)}</div><div className="kg-cart-divider"/><h2 className="kg-cart-section-title">Order summary</h2><div className="kg-summary-line"><span>Subtotal</span><span>{peso(subtotal)}</span></div><div className="kg-summary-line"><span>Delivery fee</span><span>{peso(39)}</span></div><div className="kg-summary-total"><span>Total</span><strong>{peso(total)}</strong></div></> : <div className="kg-empty kg-cart-empty"><span className="kg-empty-emoji">🛍️</span><strong>Your cart is empty</strong><span>Good food is just a few taps away.</span><Button onClick={() => navigate("menu")}>Explore menu <ArrowRight size={16}/></Button></div>}</div>}
          {screen === "failed" && <div className="kg-screen kg-failed"><div className="kg-page-header">{iconButton("Back to cart", <ArrowLeft size={19}/>, back)}{iconButton("Help", <CircleHelp size={19}/>, () => setHelpOpen(true))}</div><div className="kg-failed-content"><div className="kg-error-illustration"><span className="kg-error-card"><CreditCard size={48} strokeWidth={1.5}/></span><span className="kg-error-x"><X size={22}/></span></div><span className="kg-overline">PAYMENT UNSUCCESSFUL</span><h1>Payment didn't<br/>go through</h1><p>Your card could not be charged. Please check your card details or try another way to pay. You haven't been charged, and your order is still in your cart.</p><div className="kg-failed-order"><span>ORDER TOTAL</span><strong>{peso(total)}</strong></div><div className={`kg-recovery ${highlighted("recovery")}`}><Button className="kg-primary" disabled={retrying} onClick={() => {setRetrying(true); window.setTimeout(() => {setOrderNumber(n => n + 1);setCart([]);navigate("tracking")}, 850)}}>{retrying ? "Trying again..." : "Try payment again"} {!retrying && <ArrowRight size={16}/>}</Button><Button variant="outline" className="kg-secondary" onClick={() => navigate("cart")}>Change payment method</Button><Button variant="ghost" className="kg-text-action" onClick={() => setHelpOpen(true)}><CircleHelp size={16}/> Need help with payment?</Button></div></div></div>}
          {screen === "tracking" && <div className="kg-screen kg-tracking"><div className="kg-page-header">{iconButton("Back to home", <ArrowLeft size={19}/>, back)}<span className="kg-page-header-label">Order tracking</span>{iconButton("Help", <CircleHelp size={19}/>, () => setHelpOpen(true))}</div><div className="kg-success-visual"><span><PackageCheck size={37} strokeWidth={1.7}/></span><div className="kg-success-spark kg-spark-one">✳</div><div className="kg-success-spark kg-spark-two">✦</div></div><div className="kg-tracking-title"><span className="kg-overline">ORDER #{orderNumber}</span><h1>Good food is<br/>on its way!</h1><p>Sit tight. We're getting everything ready for you.</p></div><div className="kg-eta"><Clock3 size={19}/><div><span>ESTIMATED ARRIVAL</span><strong>25–35 minutes</strong></div><span className="kg-eta-live">LIVE</span></div><div className={highlighted("tracking")}><h2 className="kg-tracking-heading">Your order's journey</h2><div className="kg-steps">{[{title:"Order placed",description:"We've received your order",status:"done"},{title:"Preparing your food",description:"The kitchen is working on it now",status:"current"},{title:"Out for delivery",description:"Your rider will pick it up soon",status:"upcoming"},{title:"Delivered",description:"Enjoy every bite!",status:"upcoming"}].map((step, index) => <div className={`kg-step ${step.status}`} key={step.title}><div className="kg-step-track"><span className="kg-step-dot">{step.status === "done" ? <Check size={15}/> : step.status === "current" ? <span/> : null}</span>{index < 3 && <span className="kg-step-line"/>}</div><div><strong>{step.title}</strong><p>{step.description}</p>{step.status === "current" && <span className="kg-step-now">HAPPENING NOW</span>}</div></div>)}</div></div><div className="kg-tracking-help"><CircleHelp size={17}/><span>Need a hand with your order?</span><Button variant="ghost" onClick={() => setHelpOpen(true)}>Get help <ArrowRight size={14}/></Button></div></div>}
        </div>
        {screen === "detail" && <div className="kg-sticky-action kg-detail-action"><Button className="kg-primary" onClick={() => { add(selected, qty, size); navigate("cart"); }}>Add to cart <span>{peso((selected.price + (size === "Large" ? 40 : 0)) * qty)}</span></Button></div>}
        {screen === "cart" && cart.length > 0 && <div className="kg-sticky-action"><Button className="kg-primary" onClick={() => navigate("failed")}>Place order · {peso(total)} <ArrowRight size={17}/></Button></div>}
        {screen === "tracking" && <div className="kg-sticky-action"><Button variant="outline" className="kg-secondary" onClick={() => navigate("home")}>Back to home</Button></div>}
        {(screen === "home" || screen === "menu" || screen === "cart") && <nav className="kg-bottom-nav" aria-label="App navigation"><Button variant="ghost" className={screen === "home" ? "is-active" : ""} onClick={() => navigate("home")}><Home size={20} fill={screen === "home" ? "currentColor" : "none"}/><span>Home</span></Button><Button variant="ghost" className={screen === "menu" ? "is-active" : ""} onClick={() => navigate("menu")}><MenuIcon size={20}/><span>Menu</span></Button><Button variant="ghost" onClick={() => navigate("tracking")}><Clock3 size={20}/><span>Orders</span></Button><Button variant="ghost" className={screen === "cart" ? "is-active" : ""} onClick={() => navigate("cart")}><span className="kg-nav-bag"><ShoppingBag size={20}/>{count > 0 && badge}</span><span>Cart</span></Button></nav>}
        {toast && <div className={`kg-toast ${highlighted("undo")}`} role="status"><span>{toast.item.name} removed</span><Button variant="ghost" onClick={() => {add(toast.item, toast.qty, toast.size);setToast(null)}}>Undo</Button><Button variant="ghost" size="icon" aria-label="Dismiss notification" onClick={() => setToast(null)}><X size={14}/></Button></div>}
        {helpOpen && <div className="kg-overlay" onClick={() => setHelpOpen(false)}><div className="kg-help-sheet" onClick={event => event.stopPropagation()}><div className="kg-sheet-handle"/><div className="kg-help-heading"><h2>How can we help?</h2>{iconButton("Close help", <X size={18}/>, () => setHelpOpen(false))}</div><p>We're here to make your order easy.</p><div className="kg-help-faq"><div><strong>Where is my order?</strong><span>Follow each step from the Orders tab. Your estimated arrival updates as it moves along.</span></div><div><strong>Can I change my order?</strong><span>Before placing it, remove an item from your cart or pick another size.</span></div><div><strong>Payment not working?</strong><span>Try again or choose a different payment method in your cart. You won't be charged twice.</span></div></div><Button className="kg-primary" onClick={() => {setHelpOpen(false);setDialog(true)}}>Contact support <ArrowRight size={16}/></Button></div></div>}
        {dialog && <div className="kg-overlay kg-dialog-overlay" onClick={() => setDialog(false)}><div className="kg-dialog" role="dialog" aria-modal="true" aria-label="Contact support" onClick={event => event.stopPropagation()}><div className="kg-dialog-icon"><CircleHelp size={24}/></div><h2>Need a hand?</h2><p>Our team can help with orders and payments. For this prototype, explore the help topics or return to your order.</p><Button className="kg-primary" onClick={() => {setDialog(false);setHelpOpen(true)}}>View help topics</Button><Button variant="outline" className="kg-secondary" onClick={() => setDialog(false)}>Back to my order</Button></div></div>}
        {calloutsVisible && activeGuide !== null && guide[activeGuide]?.screen === screen && <div className="kg-in-app-callout" role="note"><div className="kg-callout-top"><span>HEURISTIC {guide[activeGuide]?.n}</span><Button variant="ghost" size="icon" aria-label="Dismiss callout" title="Dismiss callout" onClick={() => setActiveGuide(null)}><X size={14}/></Button></div><strong>{guide[activeGuide]?.title}</strong><p>{guide[activeGuide]?.evidence}</p></div>}
        <div className="kg-home-indicator"/>
      </div></div>
      {guideOpen && <aside className="kg-guide-panel"><div className="kg-guide-head"><div><span className="kg-guide-overline">THE DESIGN RATIONALE</span><h2>Heuristics<br/>guide<span>.</span></h2></div><Button variant="ghost" size="icon" aria-label="Close heuristics guide" title="Close guide" onClick={() => setGuideOpen(false)}><X size={18}/></Button></div><p className="kg-guide-intro">10 usability principles, made visible. Select one to see it in the app.</p><div className="kg-guide-list">{guide.map((entry, index) => <Button variant="ghost" key={entry.n} className={`kg-guide-entry ${activeGuide === index ? "is-active" : ""}`} onClick={() => selectGuide(index)}><span className="kg-guide-number">{entry.n}</span><span className="kg-guide-entry-content"><strong>{entry.title}</strong>{activeGuide === index && <span>{entry.evidence}</span>}</span><ArrowRight size={15} className="kg-guide-arrow"/></Button>)}</div><div className="kg-guide-footer"><span className="kg-guide-footer-dot"/> Nielsen's 10 usability heuristics</div></aside>}
    </main>
  </div>;
}
